language: php
php:
  - 7.1
install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
script:
  - composer run lint
  - composer run test
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
