addons:
   chrome: stable
language: php
php:
  - 7.2
before_install:
  - git config core.safecrlf false
install:
  - travis_retry composer install --no-interaction --prefer-dist
  - composer development
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
script:
  - composer lint
  - composer test
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
deploy:
  - provider: script
    skip_cleanup: true
    script: COMPOSER_PROCESS_TIMEOUT=0 composer deploy
    on:
      branch: master
