language: php
php:
  - 7.1
before_install:
  - git config core.safecrlf false
install:
  - travis_retry composer install --no-interaction --prefer-dist
  - composer development
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
script:
  - composer lint
  - composer test
  - killall chromedriver-linux
  - killall php
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
deploy:
  - provider: script
    skip_cleanup: true
    script: COMPOSER_PROCESS_TIMEOUT=0 composer deploy
    on:
      branch: master
